easy_admin:
  entities:
    Tag:
      class: 'App\Entity\Tag'
      label: Тег
      list:
        actions: ['show']
        title: tag.list_header
        fields:
          - { property: 'id', label: 'tag.id'}
          - { property: 'name', label: 'tag.name'}
      show:
        title: tag.show_header
        fields:
          - { property: 'id', label: 'tag.id' }
          - { property: 'name', label: 'tag.name' }
          - { property: 'posts', label: 'tag.posts' }
      form:
        fields:
          - { property: 'name',  type_options: { required: true, label: 'tag.name' } }
